### ISSUE TITLE
Subquery alias error in postgres 

### ISSUE THREAD

**Issue by jpmonettas** [jkk/honeysql#263] opened 2020-06-26 19:47 UTC
Hi, I'm running into the `subquery in FROM must have an alias` error when generating a sub query and attempting to run it in postgres.

```clojure
(sql/format {:select [:type]
             :from [[{:select [[:address :field-alias]]
                      :from [:Candidate]} :sub-q-alias]]}
            :parameterizer :postgresql)

;;=> ["SELECT type FROM (SELECT address AS field_alias FROM Candidate) sub_q_alias"]

```

Postgres instead of :

```
.. FROM (SELECT ...) sub_q_alias
```

seems to need :

```
.. FROM (SELECT ...) AS sub_q_alias
```

I think this issue has been already reported in https://github.com/seancorfield/honeysql/issues/184

Is there a way of getting that correctly formatted for postgres? 

Thanks!!

**Comment by seancorfield** [comment] 2020-06-26 19:58
It looks like all the databases I test `next.jdbc` against will accept `AS` for the alias in that situation so it seems a safe change to make unconditionally.

**Comment by seancorfield** [comment] 2020-06-28 18:59
Confirmed that Oracle does **not** allow `AS` there: https://clojurians.slack.com/archives/C66EM8D5H/p1593369615166200?thread_ts=1593318708.165500&cid=C66EM8D5H

**Comment by seancorfield** [comment] 2020-06-28 23:44
I'll have to give this some careful thought. In order to support PostgreSQL fully here, I'd have to break Oracle support. The goal of HoneySQL has long been to remain as database-neutral as possible and focus on the common subset of ANSI SQL that "all" databases support, but it seems increasingly likely that having `format` behave differently based on some dialect selection is going to be required. I'll try to think of a shortcut/workaround to allow for this to work for PostgreSQL in the short term.

**Comment by jpmonettas** [comment] 2020-06-29 00:47
Thanks Sean! In the meantime I'll fork it and move on with a quick hack.

**Comment by seancorfield** [comment] 2020-09-26 07:18
I believe this will be fixed in V2 based on dialect support (which V1 does not have).

**Closed as completed by seancorfield** 2020-09-26 07:18 UTC
