### ISSUE TITLE
Returning inserted values from multiple insert

### ISSUE THREAD

**Issue by JoppeSchwartz** [jkk/honeysql#304] opened 2021-02-23 21:05 UTC
We're struggling a bit trying to return inserted values from a multiple insert using `clojure.java.jdbc/execute!`.  
Without the jdbc `:multi?` option, `execute!` only returns one of the inserted rows.

So, we tried to set the `:multi?` option as in the following:
```clojure
(jdbc/execute! db
               (-> (sqlh/insert-into :test_table)
                   (sqlh/values (mapv #(assoc {} :column1 %) [1 2 3]))
                   sql/format)
               {:return-keys true
                :multi?      true})
```

When the `:multi?` option is set, `execute!` expects a vector of parameters to follow the SQL; however, the generated argument looks like 
```
["INSERT INTO test_table (column1) VALUES (?), (?), (?) RETURNING column1" 1 2 3]
```
when what we'd like to generate is 
```
["INSERT INTO test_table (column1) VALUES (?), (?), (?) RETURNING column1" [1 2 3]]
```

We obviously could have missed something, but we didn't see anything in the documentation (e.g. for `format`) that would help.

Also, we understand that our issue may be partially or completely alleviated by switching to `next.jdbc`, which is on our roadmap, but we were curious as to whether this is possible with `clojure.java.jdbc`.

FWIW we're using 
- [honeysql "1.0.444"]
- [org.clojure/java.jdbc "0.7.11"]
- [clojure.jdbc/clojure.jdbc-c3p0 "0.3.3"]
- Postgres 12

**Comment by seancorfield** [comment] 2021-02-23 23:00
Both `clojure.java.jdbc`'s `:multi?` option and `next.jdbc`'s `execute-batch!` are incompatible with the raw output of HoneySQL's `format` function. For both libraries, you will need to use a `let` binding to destructure the output of `format` and then pass the transformed data to the JDBC library.

However, you probably _can_ use HoneySQL's `format` function directly with `next.jdbc`'s regular `execute!` function and pass the `:multi-rs true` option -- that doesn't affect the _input_ argument formats (like c.j.j's `:multi?` option), only the _output_ format, which will return multiple result sets (although I'm not sure that PostgreSQL actually supports that: when I was investigating multiple result sets in `next.jdbc`, PG's support was deliberately missing parts according to posts from the maintainers on the PG forums).

I'm going to close this out as it definitely will not be natively supported in HoneySQL (neither 1.0 nor 2.0) since the issue is really the input argument formats expected in the JDBC libraries in those specific batch execution contexts -- and `next.jdbc`'s `execute-batch!` in particular is not amenable to use with HoneySQL directly because it expects you to build a `PreparedStatement` first, from a SQL string, and then call it with grouped values for the batches of SQL to execute.

I'm happy to continue discussing here how to do the destructuring and parameter grouping via regular Clojure code on top of the result of HoneySQL's `format`.

**Closed as completed by seancorfield** 2021-02-23 23:00 UTC

**Comment by JoppeSchwartz** [comment] 2021-02-24 15:11
Thanks for the quick and informative response @seancorfield ! We started taking a look at format function, and will continue that work as we migrate to `next.jdbc`. What's the best place to continue this discussion?

**Comment by seancorfield** [comment] 2021-02-24 20:09
Probably either the `#honeysql` or `#sql` channels on Slack or on Zulip (Clojurians for both).

**Comment by samrose** [comment] 2021-03-10 20:14
@seancorfield would you mind leaving an example here of 

>use a let binding to destructure the output of format and then pass the transformed data to the JDBC library.

using next.jdbc? Thanks!

**Comment by seancorfield** [comment] 2021-03-10 20:37
Off the top of my head:
```
(let [[sql & params] (sql/format {:insert-into ... :values ...})
      ps (jdbc/prepare ds [sql] {:return-keys true})]
  (jdbc/execute-batch! ps (partition n params]))
```
Where `n` is however many columns you are inserting.
