### ISSUE TITLE
Can't use :raw to specify join table

### ISSUE THREAD

**Issue by brjann** [jkk/honeysql#305] opened 2021-02-27 13:43 UTC
I am working with camel cased named tables and columns and I don't want to pollute my editor's keyword autocompletion with `:MyTable` etc. So I use `:raw` a lot to give table and column names in strings instead. 

The following works in HoneySQL 1
```Clojure
(sql/format {:select [[(sql/raw "`TheID`") :id]]
             :from   [[(sql/raw "`MyTable1`") :my-table1]]
             :join   [[(sql/raw "`MyTable2`") :my-table2] [:= (sql/raw "`my-table1`.`MyCol1`") (sql/raw "`my-table2`.`MyCol2`")]]}
            :allow-dashed-names? true
            :quoting :mysql)
=> ["SELECT `TheID` AS `id` FROM `MyTable1` `my-table1` INNER JOIN `MyTable2` `my-table2` ON `my-table1`.`MyCol1` = `my-table2`.`MyCol2`"]

```
However, the corresponding does not work in HoneySQL 2

```Clojure
(sql2/format {:select [[[:raw "`TheID`"] :id]]
              :from   [[[:raw "MyTable1"] :my-table1]]
              :join   [[[:raw "MyTable2"] :my-table2] [:= [:raw "`my-table1`.`MyCol1``"] [:raw "`my-table2`.`MyCol2`"]]]}
             {:dialect :mysql})
=> Execution error (ClassCastException) at (REPL:1).
=> null
```

Works fine without the `:join` clause
```Clojure
(sql2/format {:select [[[:raw "`TheID`"] :id]]
              :from   [[[:raw "MyTable1"] :my-table1]]}
             {:dialect :mysql})

=> ["SELECT `TheID` AS `id` FROM MyTable1 AS `my-table1`"]
```

**Comment by seancorfield** [comment] 2021-02-27 17:21
Thanks for the report. I can confirm that just formatting the `:join` on its own triggers the CCE. Almost certainly a bug (probably caused by a conflict with other aspects of `:join`'s syntax).

**Comment by brjann** [comment] 2021-02-27 18:12
Great, thanks!

**Comment by seancorfield** [comment] 2021-03-07 06:13
Fixed in next v2 release.

**Closed as completed by seancorfield** 2021-03-07 06:13 UTC
Labels: bug
