### ISSUE TITLE
Document that tuples require :composite in V2

### ISSUE THREAD

**Issue by brjann** [jkk/honeysql#314] opened 2021-03-16 14:51 UTC
I'm not sure if this is a bug. I can't remember where I located the syntax that made this work in HoneySQL 1, so maybe it should not have worked there.

Honey SQL 1
```Clojure
(sql/format {:select [:id]
             :from   [:table]
             :where  [:in [:col1 :col2] [[1 2] [3 4]]]})

=> ["SELECT id FROM table WHERE ((col1, col2) in ((?, ?), (?, ?)))" 1 2 3 4]
```
The matching of tuples in the `IN` clause is correctly identified .

Honey SQL 2
```Clojure
(sql/format {:select [:id]
             :from   [:table]
             :where  [:in [:col1 :col2] [[1 2] [3 4]]]})

=> ["SELECT id FROM table WHERE COL1(col2) IN ((?, ?), (?, ?))" 1 2 3 4]
```
`[:col1 :col2]` is identified as a function call `COL1(col2)`

I hope that I am not bothering you with a non-bug again!

**Comment by seancorfield** [comment] 2021-03-16 16:28
This is an interesting one. V1 was pretty inconsistent about whether it treated `[:kw ...]` as a function call or not whereas V2 is very consistent: `[:kw ...]` is _always_ a function call. I suspect this "worked by accident" in V1 but it is certainly a useful construct so I'll see whether there's already a way to do this in V2 or whether I'll need to add some additional syntax.

**Comment by seancorfield** [comment] 2021-03-16 16:32
Confirmed that it works in 1.0 and 0.9 releases so it's been supported for quite a while. It will definitely need a slightly different syntax in V2 since `[:kw ...]` has to resolve to a function call "everywhere".

**Comment by seancorfield** [comment] 2021-03-16 16:36
Ah, yes. `:composite` is what's needed here:
```clojure
user=> (sql/format {:select [:id]
  #_=>              :from   [:table]
  #_=>              :where  [:in [:composite :col1 :col2] [[1 2] [3 4]]]})
["SELECT id FROM table WHERE (col1, col2) IN ((?, ?), (?, ?))" 1 2 3 4]
```
There's also a helper so `(composite :col1 :col2)` would work as well.

I'll make this a documentation issue and close it once I've updated the docs.

**Comment by brjann** [comment] 2021-03-16 16:48
Thanks!

**Comment by seancorfield** [comment] 2021-04-10 01:07
Docs updated for V2.

**Closed as completed by seancorfield** 2021-04-10 01:07 UTC
Labels: documentation
