### ISSUE TITLE
:values can be formatted out of order when using a vector of maps

### ISSUE THREAD

**Issue by snoe** [jkk/honeysql#144] opened 2016-11-24 22:15 UTC
https://github.com/jkk/honeysql/blob/d07a1a376467c2a05266553d017ec09a97b83ee5/src/honeysql/format.cljc#L531-L534

there's an incorrect assumption in the code here that `(first (keys values))` will return keys in the same order for every call of `(for [x values] (vals x))` 

I don't have time for a pr but the code I used to work around this is in my user code is something like:

```clj
(let [cols (vec (set (mapcat keys values)))
      vals (map (apply juxt cols) values)]
  {:insert-into table
   :columns cols
   :vals vals})
```

**Comment by MichaelBlume** [comment] 2016-12-05 22:36
Sorry, can you give a simple reproducing test case?

**Comment by snoe** [comment] 2016-12-09 17:49
@MichaelBlume this probably differs based on machine/jvm but notice that the second set of values is backwards.

```clojure
(hformat/format {:values [{:a 1 :b 2 :c 3}
                          (hash-map :a 1 :b 2 :c 3)]})
=> ["(a, b, c) VALUES (1, 2, 3), (3, 2, 1)"]
(hash-map :a 1 :b 2 :c 3)
=> {:c 3, :b 2, :a 1}
{:a 1 :b 2 :c 3}
=> {:a 1, :b 2, :c 3}

```

**Comment by vincent-dm** [comment] 2017-04-09 14:43
I also got bitten by this. I am trying to insert an array of maps, but their keys are not in the same order and get placed in the wrong order in the generated SQL bindings.

**Comment by MichaelBlume** [comment] 2017-04-11 00:51
This looks like it was fixed in #154

**Comment by MichaelBlume** [comment] 2017-04-11 00:52
(Which has not been released yet, but is in master)

**Closed by MichaelBlume** 2017-04-11 00:52 UTC

**Comment by vincent-dm** [comment] 2017-04-25 13:02
@MichaelBlume any idea when the fix will be released? Our workaround really messes up the codebase as-is... Thanks!

**Comment by MichaelBlume** [comment] 2017-05-10 20:26
I'll try to have a release out today or tomorrow
